### ISSUE TITLE
lock-collection logic needs fixed

### ISSUE THREAD

**Issue by bmacer** [rmrk-team/rmrk-substrate#10]
lock collection sets max to currently-minted.  so someone could then burn and re-mint, which doesn't lock.
perhaps set max to one less than the currently-minted, then add a check when *burning* so if currently_minted < max (and not zero) then burning is not allowed.

**Comment by HashWarlock** [comment]
Correct me if I'm misinterpreting this, but we wouldn't decrement the amount of minted NFTs when we burn an NFT within a collection, right? At least that is what I ran into with RMRK 1.0 Collections before. Burning would only destroy the NFT, but the NFTs minted in the collection count would remain the same.

**Comment by gorillatron** [comment]
Just asking to see if I am reading correctly. This issue is fixed in the current main branch?
In `pallets/rmrk-core/src/lib.rs` at:

`pub fn mint_nft(`
`...`
```rust
let collection =
    Self::collections(collection_id).ok_or(Error::<T>::CollectionUnknown)?;

let nfts_minted = NFTs::<T>::iter_prefix_values(collection_id).count();
let max: u32 = collection.max.try_into().unwrap();

ensure!(
    // Probably a better way to do "max == 0"
    nfts_minted < max.try_into().unwrap() || max == max - max,
    Error::<T>::CollectionFullOrLocked
);
```

_Poking around the code to see if I can learn something and maybe even contribute down the line._ 🤓
