### ISSUE TITLE
Benchmark RMRK-Core pallet

### ISSUE THREAD

**Issue by ilionic** [rmrk-team/rmrk-substrate#106]
Add weights especially with deep nested and [many] multi resource NFTs.

**Comment by bmacer** [comment]
Begun work on benchmarking here: https://github.com/rmrk-team/rmrk-substrate/tree/bug/106-benchmarking

One early challenge I see is... don't we need to have a `MaxChildPerNft` value?  We have a MaxRecursions, which goes into generations, but won't it be impossible to benchmark `burn_nft`, for example, without a limit on children?

**Comment by yornaath** [comment]
👍 Yes benchmarks is perhaps the biggest blocker for us at zeitgeist to be able to implement the rmrk pallets.

**Comment by ilionic** [comment]
Benchmarking PR has been merged
