### ISSUE TITLE
NftsByOwner storage isn't updated anywhere

### ISSUE THREAD

**Issue by MrShiposha** [rmrk-team/rmrk-substrate#108]
`NftsByOwner` storage seems to be very useful since the frontend might be interested in fetching all the NFTs owned by a specific user.
https://github.com/rmrk-team/rmrk-substrate/blob/3a1e5cc3e9b9da0a01b5667916b646e62e5147a2/pallets/rmrk-core/src/lib.rs#L90-L94

But for now, this storage is updated only at NFT minting.
https://github.com/rmrk-team/rmrk-substrate/blob/3a1e5cc3e9b9da0a01b5667916b646e62e5147a2/pallets/rmrk-core/src/functions.rs#L214

It never updates at send/burn and all the rest interactions.

Thus it cannot be used to obtain up-to-date ownership info.

Also, maybe this storage supposed to be `StorageNMap` instead of `StorageMap` with `Vec<_>` (as suggested in [another issue](https://github.com/rmrk-team/rmrk-substrate/issues/48#issuecomment-1012300045))?
And maybe this storage is just a duplicate of uniques `Account`? See the comments of #48

**Comment by h4x3rotab** [comment]
I believe we should remove `NftsByOwner` and use `pallet-uniques`'s `Account` storage to get a list of the NFTs by an owner.

**Comment by bmacer** [comment]
removed in #91
