### ISSUE TITLE
Rejecting NFT leads to its burn

### ISSUE THREAD

**Issue by MrShiposha** [rmrk-team/rmrk-substrate#109]
When NFT is sent to another NFT owned by another user, it is removed from the `Nfts` storage and placed into the `PendingNfts` storage.
https://github.com/rmrk-team/rmrk-substrate/blob/3a1e5cc3e9b9da0a01b5667916b646e62e5147a2/pallets/rmrk-core/src/functions.rs#L309-L312

There is a dangerous thing: when the target NFT's owner decides to reject the pending NFT, this NFT will be just removed from the `PendingNfts` and **won't be placed back into the `Nfts`**.
Also, if this NFT was owned by some parent NFT, **it won't be inserted into the list of children of the parent NFT**. 
https://github.com/rmrk-team/rmrk-substrate/blob/3a1e5cc3e9b9da0a01b5667916b646e62e5147a2/pallets/rmrk-core/src/functions.rs#L394-L411

----

NOTE: Resources can also be in the "pending" state. But there is no additional storage for pending resources. There is a flag indicating that the resource is "pending". Maybe it is easier to have a similar flag in the `NftInfo` instead of using two mutually exclusive storages?
https://github.com/rmrk-team/rmrk-substrate/blob/3a1e5cc3e9b9da0a01b5667916b646e62e5147a2/pallets/rmrk-core/src/functions.rs#L85-L96

**Comment by HashWarlock** [comment]
I agree. Storing 2 separate Storages causes a problem. I'll check on clarification since I do not see the reject function in the NFT spec right now. I do think something similar to how resources are accepted could be reasonable or add an enum for the Pending state if there are multiple states a NFT could be in.

**Comment by HashWarlock** [comment]
Looks like when a NFT is rejected we should burn the NFT. I'll mark this as a bug. We can also add the `pending` flag to `NftInfo` Storage to simplify the storage as you suggest. @ilionic what're your thoughts?

**Comment by ilionic** [comment]
Yeah, this is expected re. rejected NFT to burn. 
I think this is good call to have `pending` on `NftInfo` to keep things consistent. @bmacer wdyt?

**Comment by bmacer** [comment]
This pending flag sounds much more reasonable.  Not sure why I implemented it in such a complicated way initially.  Anyway sounds good to me moving in this direction.  Just need to be sure we recursively update pending for all children on both send and accept_nft actions.
