### ISSUE TITLE
Change Issuer Doesn't Change Issuer in Pallet Uniques ClassDetails

### ISSUE THREAD

**Issue by HashWarlock** [rmrk-team/rmrk-substrate#114]
Currently there is only a change to the `Collections` StorageMap value `CollectionInfo` `issuer`. When querying `pallet_uniques` `ClassDetails` of the current `issuer` after the change, it will reflect the previous `issuer`. To avoid this, we would need to call `pallet_uniques` `set_team` and change the `owner`, `issuer` and `freezer` to the new `issuer` since RMRK Collections only retain the `issuer` in `CollectionInfo`.

**Comment by ilionic** [comment]
Tested in https://github.com/rmrk-team/rmrk-substrate/pull/122 fixed.
