### ISSUE TITLE
Resource priorities can be set by anyone

### ISSUE THREAD

**Issue by MrShiposha** [rmrk-team/rmrk-substrate#116]
There are no permission or NFT existence checks when setting resource priorities on NFT.

https://github.com/rmrk-team/rmrk-substrate/blob/27f9e27b784d223b9e4ec05dc9817293c6b8e4d6/pallets/rmrk-core/src/functions.rs#L17-L32

https://github.com/rmrk-team/rmrk-substrate/blob/27f9e27b784d223b9e4ec05dc9817293c6b8e4d6/pallets/rmrk-core/src/lib.rs#L663-L673

**Comment by ilionic** [comment]
Thanks, fixed in https://github.com/rmrk-team/rmrk-substrate/pull/122
