### ISSUE TITLE
The collection can be locked by anyone

### ISSUE THREAD

**Issue by h3lpkey** [rmrk-team/rmrk-substrate#117]
Hi! There is no check when you lock a collection, so anyone can close someone else's collection.

https://github.com/rmrk-team/rmrk-substrate/blob/27f9e27b784d223b9e4ec05dc9817293c6b8e4d6/pallets/rmrk-core/src/lib.rs#L538-L548

https://github.com/rmrk-team/rmrk-substrate/blob/27f9e27b784d223b9e4ec05dc9817293c6b8e4d6/pallets/rmrk-core/src/functions.rs#L229-L236

**Comment by ilionic** [comment]
Thanks, fixed in https://github.com/rmrk-team/rmrk-substrate/pull/122
