### ISSUE TITLE
Split add_resource - composable v non-composable

### ISSUE THREAD

**Issue by bmacer** [rmrk-team/rmrk-substrate#120]
I think the add_resource extrinsic would be cleaner if it were split into add_composable_resource and add_noncomposable_resource.  I find this generally to be the case with the RMRK standard (recognizing two distinct resource types) but might be wise to implement this way.

Alternatively, could implement an enum Resource::Composable and Resource::NonComposable and use that as the input instead of just the flattened all-possible-properties as it currently exists.

**Comment by bmacer** [comment]
Going further, I think it might be helpful to have three Resources in an enum: `BasicResource` (no base or slot), `ComposableResource` (includes `base` reference, and `parts`, but no `slot`), and `SlotResource` aka NoncomposableResource (includes `base` and `slot`, but no `parts`).  I think dividing into three will help logical understanding of Resources.

**Comment by ilionic** [comment]
Agree, this is major mental overhead in current kusama rmrk2 version.
