### ISSUE TITLE
What's the intended ProtocolOrigin

### ISSUE THREAD

**Issue by KaiserKarel** [rmrk-team/rmrk-substrate#13]
Currently ProtocolOrigin is able to bloat/block the chain, as the metadata is not a BoundedVec. It is not a security risk if protocol origin is Root, and the input is checked in a different location, but still best to add a check.

**Comment by ilionic** [comment]
Thanks for suggestion. Started updating metadata to BoundedVec https://github.com/rmrk-team/rmrk-substrate/commit/f5b02f20a2b3e878e070ff04107782b628397b62#diff-abd1b2803dd61ebf47dadb21412dacab4284af5b4b074f81e6d983c21e4f7fe3R303
