### ISSUE TITLE
Replace iter_prefix with drain_prefix to burn children NFTs

### ISSUE THREAD

**Issue by HashWarlock** [rmrk-team/rmrk-substrate#131]
Currently we iterate through the children then could `drain_prefix` inside the `iter_prefix` on the parent NFTs. This is unnecessary as we can utilize `drain_prefix` instead which will remove the parent NFT then recursively call the `burn_nft` that will burn the children NFTs. 

Here is an example of the current code.
https://github.com/rmrk-team/rmrk-substrate/blob/ead0e1e8c64ec00518f9472b0facd05c4a010743/pallets/rmrk-core/src/functions.rs#L321-L324

Instead we would use `drain_prefix` to get the child NFTs as we iterate the `Children` Storage. Then we call the `burn_nft` to take care of burning the children and their children as well.
```
 for ((child_collection_id, child_nft_id), _) in Children::<T>::drain_prefix((collection_id, nft_id,)) {  
 	Self::nft_burn(child_collection_id, child_nft_id, max_recursions - 1)?; 
 } 
```

**Comment by bmacer** [comment]
Does this do it? #134
