### ISSUE TITLE
Ids contradiction

### ISSUE THREAD

**Issue by MrShiposha** [rmrk-team/rmrk-substrate#138]
### Resource Id
There are different representations of the Resource Id.

#### 1) u32 representation
One is in the `rmrk-traits`:
 https://github.com/rmrk-team/rmrk-substrate/blob/0bcc42a204763d1ee27a58d5318763c87b6eaf86/traits/src/lib.rs#L23

It is used in `NextResourceId` storage:
https://github.com/rmrk-team/rmrk-substrate/blob/0bcc42a204763d1ee27a58d5318763c87b6eaf86/pallets/rmrk-core/src/lib.rs#L92

And it is used in the priorities:
https://github.com/rmrk-team/rmrk-substrate/blob/0bcc42a204763d1ee27a58d5318763c87b6eaf86/pallets/rmrk-core/src/lib.rs#L113-L118

----

#### 2) string representation
Another representation of the resource Id is `BoundedVec<u8, ResourceSymbolLimit>`:
https://github.com/rmrk-team/rmrk-substrate/blob/0bcc42a204763d1ee27a58d5318763c87b6eaf86/pallets/rmrk-core/src/lib.rs#L31-L35

### Unused resource Id generation
The `NextResourceId` used only in `get_next_resource_id` function which is never used:
https://github.com/rmrk-team/rmrk-substrate/blob/0bcc42a204763d1ee27a58d5318763c87b6eaf86/pallets/rmrk-core/src/functions.rs#L657-L663

### Part Id
Unused Id generation. The Id is taken from the `create_base` extrinsic input.
Storage `NextPartId` and the function `get_next_part_id` are unused.

### Observation about IDs
In the RMRK spec, parts and resources obtain their IDs from some external generator (like the nanoid).
It seems it is intended to generate IDs internally in the `rmrk-substrate` (as far as I can understand from the code).
But ids are still expected from the inputs.

**Comment by bmacer** [comment]
The auto-generated resource id is the functionality we should have.  My previous belief was that it would be more convenient to assign a resource Id (in fact all ids would be my preference) but Bruno alerted to the priority of minimal space consumption on-chain.

I'll work on fixing this asap.
