### ISSUE TITLE
Adding traits to describe the total interface.

### ISSUE THREAD

**Issue by KaiserKarel** [rmrk-team/rmrk-substrate#14]
Right now the core pallet exposes most functionality through extrinsics. We should consider defining traits for the entire rmrk-ecosystem, which are implemented by the pallet, and having the extrinsics calling these trait methods. This makes pallet-to-pallet calls easier as well.

**Comment by ilionic** [comment]
Thanks @KaiserKarel 
Initial progress on traits (Collection) just merged. We will continue abstracting away traits as we go. 
https://github.com/rmrk-team/rmrk-substrate/blob/main/traits/src/collection.rs#L19

**Comment by ilionic** [comment]
All main traits from core pallet have been extracted https://github.com/rmrk-team/rmrk-substrate/tree/main/traits/src
