### ISSUE TITLE
Implement non-transferable items

### ISSUE THREAD

**Issue by ilionic** [rmrk-team/rmrk-substrate#141]
[RMRK2 spec](https://github.com/rmrk-team/rmrk-spec/blob/master/standards/rmrk2.0.0/entities/nft.md#nft) contains `transferable` property currently missing in pallets. ( Needed for ie Kanaria gems and all the "soulbound" mechanics. )

In Kusama’s implementation we also have a modifier for temporary transferability, so that you can say, this becomes non transferable after X blocks, or it is transferable for only X blocks, but to not complicate things just the basic boolean would do.

**Comment by HashWarlock** [comment]
For Phala World, we use the `InstanceDetails` property `is_frozen` bool to accomplish this. We call the `pallet_uniques::Pallet::<T>::freeze(origin: OriginFor<T>, collection_id: CollectionId, nft_id: NftId)` to `freeze` the NFT from being transferred. Only the Class Owner or the dedicated `Freezer` account can freeze NFTs.
