### ISSUE TITLE
Add Resource During Mint Process

### ISSUE THREAD

**Issue by HashWarlock** [rmrk-team/rmrk-substrate#146]
Currently we have to add the Resource after Minting a NFT in Phala World which requires the owner to `accept_resource` to get a resource for the NFT. I would suggest to add another parameter for a Resource to be added during the minting process to avoid adding a Resource & requiring the new owner to accept the NFT.

**Comment by bmacer** [comment]
100% great idea, shouldn't be too taxing to implement either, simple Option<Resource>...maybe.  Famous last words.  I'll give it a try. :D

**Comment by bmacer** [comment]
should we have a BoundedVec option to allow for a vec of resources to be added on mint, or just a single resource?

**Comment by HashWarlock** [comment]
> should we have a BoundedVec option to allow for a vec of resources to be added on mint, or just a single resource?

Good question. I guess it depends. Seems there could be a use case to build a composable resource by having a BoundedVec. Though that could be a reason to create another function for composable resource flow.

**Comment by ilionic** [comment]
> should we have a BoundedVec option to allow for a vec of resources to be added on mint, or just a single resource?

That would be ideal, quite common use case to mint with multiple resources ( even non composable )

**Comment by SupremaLex** [comment]
@HashWarlock, correct me if I am not right. Do your original intention was to avoid the required acceptance of resources by the NFT owner during the mint process? Because right now we just call `resource_add` for each resource passed as an argument, so the item owner still needs to accept it.

**Comment by HashWarlock** [comment]
> @HashWarlock, correct me if I am not right. Do your original intention was to avoid the required acceptance of resources by the NFT owner during the mint process? Because right now we just call `resource_add` for each resource passed as an argument, so the item owner still needs to accept it.

Yes, this was originally an ask to be able to add the resource at mint instead of having to do `resource_add` after doing the mint which requires the user to accept. Right now in Phala World we do a work around by using the `metatdata` to define the first resource.
