### ISSUE TITLE
Decouple Equip Logic

### ISSUE THREAD

**Issue by HashWarlock** [rmrk-team/rmrk-substrate#147]
Currently the Equip Pallet's `equip` function handles the following scenarios:
1. Removes NFT to equip if the NFT has been burned & is present in `Equippings` storage
  -  Mutates `Nfts` field `equipped` sets to `false`
  -  Removes from `Equippings` then triggers a `SlotUnequipped`
2. Removes NFT to equip if NFT is equipped and called by the `root_owner` or `equipper_owner`
  -  Mutates `Nfts` field `equipped` sets to `false`
  -  Removes from `Equippings` then triggers a `SlotUnequipped`
3. Equips NFT if the direct parent of NFT is the NFT to be equipped to with a valid `BaseId` & `SlotId`
  - If Resource already exists in `BaseId` & `SlotId` then it will replace the previous Resource.
  - If no Resource exists and valid `BaseId` & `SlotId` then the new Resource is equipped.

I recommend creating 2 separate functions:
- `equip(origin, nft_to_equip: (CollectionId, NftId), parent_nft: (CollectionId, NftId), parent_resource_id: ResourceId, resource_id_to_equip: ResourceId, base: BaseId, slot: SlotId)`
  - Handles equipping Resources to a NFT with open `BaseId` and `SlotId`. Instead of iterating through the Resources of the NFT to be equipped, we can pass in the `ResourceId` as well since UI can handle finding the right `ResourceId`
  - Replaces NFT equipped with the compatible ResourceId
- `unequip(origin, nft_to_equip: (CollectionId, NftId), parent_nft: (CollectionId, NftId), parent_resource_id: ResourceId, resource_id_to_unequip: ResourceId, base: BaseId, slot: SlotId)`
  - Handles points 1) and 2) and removes the equipped NFT

Since all the information will be on the blockchain, we can leave iterating through storage to find the right ResourceId to be equipped to the parent ResourceId w/ a compatible `BaseId` and `SlotId` to UI development to query and ensure they have correct info for parameters to be able to equip the NFT.

Another suggestion would be restructuring the `ResourceInfo` to have an enum `ResourceType` to differentiate between the different resources that a resource can be. From my understanding, there can be 3 types: Basic Media, Composable Base & Composable Parts. Separating these types can make the struct for `ResourceInfo` better to understand & can help with detecting the `ResourceType` quicker to ensure the equip functions can better handle logic.

Any thoughts on this and if there are other optimizations I may be missing?

**Comment by bmacer** [comment]
I'm happy to see your suggestion going in the direction of *including* the ResourceId in the equip/unequip operations.  I agree that equip and unequip should be decoupled.  I can work on that.

As for the enum `ResourceType`, this is implemented in #145, unless you disagree?

https://github.com/rmrk-team/rmrk-substrate/blob/20235f9c72c2fff13074979a0d4d83fff76da067/traits/src/resource.rs#L111-L128

`ResourceInfo` becomes just a shell for allowing `pending` actions (even the `id` I *think* might be disposable if we accept the additional changes in commit https://github.com/rmrk-team/rmrk-substrate/commit/20235f9c72c2fff13074979a0d4d83fff76da067.  But the important part is the reference to this enum `ResourceTypes`, which does exactly as you're describing.

https://github.com/rmrk-team/rmrk-substrate/blob/20235f9c72c2fff13074979a0d4d83fff76da067/traits/src/resource.rs#L103-L109

I'd recommend we consider if #145 is good to merge (especially with regards to the new commit https://github.com/rmrk-team/rmrk-substrate/commit/20235f9c72c2fff13074979a0d4d83fff76da067), then just treat this issue as a decoupling of equip/unequip, unless I'm misunderstanding your suggestion.  We could also add removing ID from the struct to this issue.

**Comment by HashWarlock** [comment]
Yeah, I agree. I'll make some comments on PR if I have anymore, but I think this is a good direction and we can optimize anything else we may run into.
