### ISSUE TITLE
Incorrect burning of a child NFT

### ISSUE THREAD

**Issue by MrShiposha** [rmrk-team/rmrk-substrate#148]
When burning child NFT it won't be removed from the **owner-NFT's** children list.

**Comment by bmacer** [comment]
thanks for reporting, pretty sure PR #149 will fix it gracefully.  added a test and the fix.

**Comment by MrShiposha** [comment]
@bmacer yes, the burning child NFTs is fixed now.
But still, there is an issue with Reject NFT.

Here is an example:
* Alice creates a collection `collectionId = 0`
* using this collection, Alice mints token for herself `nftId = 0`
* using this collection, Alice mints token for Bob `nftId = 1`
* Bob sends `nftId = 1` to `nftId = 0`
* Alice rejects `nftId = 1`, but still, we can see it in the children list of the `nftId = 0`.

The issue comes up from the fact, that NFT will be rewritten in the `Nfts` storage only if no approval is required.
If approval **is** required, then _only pending flag will be set, but owner field **will not** be updated_.

https://github.com/rmrk-team/rmrk-substrate/blob/82e1bd5b8b7f19cba0e8b1f6c43e986631011caa/pallets/rmrk-core/src/functions.rs#L394-L407

I believe it could be fixed if you rewrite the above to this:
```rust
sending_nft.owner = new_owner;
sending_nft.pending = approval_required;
Nfts::<T>::insert(collection_id, nft_id, sending_nft);
```

**Comment by bmacer** [comment]
I don't think the solution is quite so simple.  We don't want Bob to be able to send Bob-owned NFT (0,1) to Alice-owned NFT (0, 2) without acceptance.  As it stands, it looks like 'accept' will allow the acceptor to accept on to any owned NFT, which is itself probably not ideal.  The intended recipient should probably be the only acceptable NFT.  As such, I think we should adjust the logic and NFT struct.  I propose changing 'pending' from a bool to an Option<(CollectionId, NftId)>.  Then, for a qualified send, the owner changes to the root owner, and the pending becomes Some((CollectionId, NftId)).  The Children storage doesn't change here, instead it changes on 'accept', which will update the owner to the NFT and which also now is limited to being accepted to this NFT.  Reject would burn the NFT but would have no need for touching the Children storage.

**Comment by bmacer** [comment]
Looked at it again, seems the fix wasn't too complicated, just needed to adjust the `reject` logic some.  Pending code review but test passed, looks good.
