### ISSUE TITLE
Release polkadot-vx.x.x branch for each polkadot release as Substrate & Cumulus does

### ISSUE THREAD

**Issue by jasl** [rmrk-team/rmrk-substrate#153]
Hi, this is PhalaNetwork, we're integrating RMRK pallets to our parachain

There's a challenge for parachain is we have to follow `polkadot-v0.x.x` campanion branch of Substrate.

Now the current main branch uses `polkadot-v0.9.22`, but if Parity release `0.9.23`, and the parachain willing to upgrade, it will unmatch.
Another case is if a parachain not willing to upgrade latest version, Cargo are always trying to get the latest commit of a branch, it may also lead unmatch.

Above 2 case may lead dependencies hell trouble,
so I propose RMRK make Polkadot campanion branch too.

**Comment by HashWarlock** [comment]
I've started creating new branches starting at [polkadot-v0.9.24](https://github.com/rmrk-team/rmrk-substrate/tree/polkadot-v0.9.24) & will look to branch off every upgrade like in #197
