### ISSUE TITLE
Resources should have assignable (not auto-incrementing) IDs, at least optionally

### ISSUE THREAD

**Issue by bmacer** [rmrk-team/rmrk-substrate#169]
Similar to Collection/Nfts discussed here https://github.com/rmrk-team/rmrk-substrate/issues/83

Front-end implementations seem to be urging for the option of assigning your own ResourceID number, which would allow for "knowing" the ID ahead of time, instead of relying on the event revealing the ID assigned.

Opening this to document the conversation/discussion.

**Comment by ilionic** [comment]
Based on numerous discussion about general IDs strategy here we could: 

* collection id - keep auto increment id ( make sense to return id upon creation ) 
* nft id - remove auto increment ( similar to pallet uniques )
* resource id - also remove auto increment
