### ISSUE TITLE
Additional parameters for burn_nft

### ISSUE THREAD

**Issue by MrShiposha** [rmrk-team/rmrk-substrate#172]
It seems that the current weight of `burn_nft` is too small because it is a recursive transaction.

A benchmark should be written to generate the appropriate weight for the transaction.
Despite it can be written later, there is an architectural question -- what signature should the `burn_nft` have?

I believe it is essential to have additional parameters like `max_recursions` to actually be able to write a correct benchmark. For `burn_nft`, it would be needed to have even 2 additional parameters (like `max_burns` and `max_breadth`) because the weight of actually burning an NFT differs from the weight of traversing an NFT bundle during the burn transaction.

Also, it would be good to use only one argument of some `struct` type.
Here is why:
  * You can't mess up the order of the limit arguments (like `max_burns` and `max_breadth`)
  * You can easily add something to it
  * You can make optional arguments with default values

**Comment by MrShiposha** [comment]
It seems there are two options:
* Add new parameters to burn_nft
* Add constants to Config that will limit max NFT bundle depth and number of children per NFT

-----

The second option seems to be really costly. Because the deeper you go, the more potential children you need to burn.
The total number of NFTs you need to burn would be `1 + MaxChildren + MaxChildren^2 + ... + MaxChildren^(MaxDepth)`.

A benchmark should take into account the worst case, so the weight of the `burn_nft` could be large.
Moreover, it could be large even for NFTs without children. Of course, you can utilize the [DispatchResultWithPostInfo](https://docs.rs/frame-support/latest/frame_support/dispatch/type.DispatchResultWithPostInfo.html) to return the actual weight. But a user is still required to have enough balance to pay the declared fee amount despite the fact that the user will receive all unused means back.

-----

The first option allows you to adjust the transaction weight according to the maximum number of NFTs a user is expecting to burn. So you could add the `max_burns` parameter for that.

But you can mitigate the transaction cost even further. A user might know how wide is the NFT tree. Since the burning operation is much more expensive than the transition between children, you can benchmark the transition cost and you can adjust the transaction weight by another additional parameter `max_breadth`.

To do so, you need to write 2 benchmarks:
1. A benchmark for burning a single NFT without children.
```rust
burn_single_nft {
    // Mock an account, create a collection...

    mint_nft(/* params for the NFT here */)?;
    // We need to obtain collection id and NFT id....

    let max_burns = /* the maximum burns you're expecting */
    let max_breadth = /* the maximum tree breadth you're expecting */
}: {<Pallet<T>>::burn_nft(account, <collection_id>, <nft_id>, max_burns, max_breadth)}
``` 
2. A benchmark for burning an NFT with children.
```rust
burn_nft_with_children {
    let b in 0..200;
    
    // Mock an account, create a collection...

    // Mint the root NFT     
    mint_nft(/* params for the NFT here */)?;

    for i in 0..b {
        /* mint an NFT and send it to the root one */
    }

    let max_burns = /* the maximum burns you're expecting */
    let max_breadth = /* the maximum tree breadth you're expecting */
}: {<Pallet<T>>::burn_nft(account, <root_collection_id>, <root_nft_id>, max_burns, max_breadth)}
```

Then you can extract the cost of the transition between children:
```rust
    fn burn_nft_transition_weight(amount: u32) -> Weight {
        WeightInfo::burn_nft_with_children(amount)
            .saturating_sub(WeightInfo::burn_single_nft().saturating_mul(amount + 1))
    }
```

And finally, we are ready to define a function returning the weight of the `burn_nft`:
```rust
    fn burn_nft_weight(max_burns: u32, max_breadth: u32) -> Weight {
        WeightInfo::burn_single_nft()
            .saturating_mul(max_burns.max(1))
            .saturating_add(burn_nft_transition_weight(max_breadth))
    }
```

**Comment by MrShiposha** [comment]
Yes it is possible but the weight will be bigger

**Comment by MrShiposha** [comment]
By the way, I forgot to mention that `max_burns` is also needed for `reject_nft`.

**Comment by bmacer** [comment]
I'm not sure why only `max_burns` would make it heavier, can you clarify?

I started to implement an attempt at a solution, and pushed #174, because at the surface, it seems like a super-simple solution...just "expose" the `MaxRecursions` parameter to the extrinsic.  Is this sufficient as a solution?  Certainly would still need to benchmark (which I'm still learning about) but if it can be as simple as this, that'd be great.

Let me know your thoughts/feedback.

**Comment by MrShiposha** [comment]
I just realized that in this case, the only way is to have one `max_burns` param.
I initially thought about burning leaves nodes and walking up the tree. In such a case, separating the transition and burn costs is reasonable.

I see that in `burn_nft` we are burning NFT on each step. So there is no need to compute the transition cost separately.
`max_burns` would work!
