### ISSUE TITLE
NFT listing

### ISSUE THREAD

**Issue by mrshiposha** [rmrk-team/rmrk-substrate#186]
One is allowed to **partially** unlist an NFT via the `list` extrinsic:
 https://github.com/rmrk-team/rmrk-substrate/blob/1139b405ce39243da6fca1be062d4ff3cd7f2879/pallets/rmrk-market/src/lib.rs#L255-L260

But this NFT will be locked forever.

I suggest forbidding unlisting through the `list` extrinsic. I believe that the `unlist` extrinsic is enough.

**Comment by HashWarlock** [comment]
This is to update the listing if it exists. We could change this to a `try_mutate` instead on the `ListedNfts` to prevent the temporary removal from storage.

**Comment by MrShiposha** [comment]
Oh sure, I got confused, sorry :)

**Comment by HashWarlock** [comment]
Agreed we can submit this as a simple refactor.
