### ISSUE TITLE
docker_run.sh not working: missing .local

### ISSUE THREAD

**Issue by pstuermlinger** [rmrk-team/rmrk-substrate#239]
`docker-compose.yml` tries to mount a .local file/folder(?). It's included in `.gitignore` so it seems like I should create it on my own. What should it contain?

```
./docker_run.sh cargo check
*** Start Substrate node template ***
[+] Running 1/1
 ⠿ Network rmrk-substrate_default  Removed                                                                                                               0.2s
[+] Running 1/0
 ⠿ Network rmrk-substrate_default  Created                                                                                                               0.0s
Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /home/user/projects/rmrk-substrate/.local
```

**Comment by ilionic** [comment]
docker-compose and docs around it came from [substrate-node-template](https://github.com/substrate-developer-hub/substrate-node-template/blob/main/docker-compose.yml) but aren't actively used by contributors in this repo so setup should be double checked and most likely improved.
We might need to keep an eye on following PR from template repo https://github.com/substrate-developer-hub/substrate-node-template/pull/385

**Comment by jamesbayly** [comment]
We've just tested https://github.com/substrate-developer-hub/substrate-node-template/pull/385 so are behind it as the best practice docker compose file from RPC providers point of view
