### ISSUE TITLE
Parameter types considered harmful

### ISSUE THREAD

**Issue by h4x3rotab** [rmrk-team/rmrk-substrate#24]
_Parameter types_ are the generic associate types that can be specified in the `Config` trait of each pallet. For example, `CollectionId`, `NftId`, and `ResourceId` in the rmrk core pallet:

https://github.com/rmrk-team/rmrk-substrate/blob/39bc9f143e513f588d97752df0dd356d2e702f4c/pallets/rmrk-core/src/lib.rs#L66-L85

This pattern is widely used in FRAME and ORML. It's very powerful -- that's how Moonbeam makes the AccountId fully compatible with Ethereum. However in other cases, it's generally over-design. Substrate often got criticized by making the generic type system over complicated.

The Balances pallet allows you to specify the type of the balance. Suppose we have two parachains,  one with `u128` and another with `u32`, then how can they communicate in xcmp? It turned out in XCM all the assets has a fixed type, `u128`, in order to allow the participants to understand each other.

If we follow this pattern, not only it introduces the code complexity, but also it can result in ecosystem fragmentation. Imagine 10 parachains with 10 different instance of the RMRK pallets, it will be problematic when doing the XCM. Even for Substrate, there's a light version called smoldot that largely reduced the generic type usage in the codebase.

Do we really need to allow the downstream to change the types? There are generally 4 kinds of types, and IMO they can be treated differently:

1. Constants: nice to keep, because it's likely the downstream wants to customized it (e.g. `DepositPerByte` in pallet-unique)
2. Permission: nice to keep, for the same reason as constants (e.g. `ProtocolOrigin ` in rmrk-core)
3. Injected dependency: nice to keep (e.g. `Currency` used everywhere)
4. Generic type: don't use until absolutely necessary

So my suggestion: define the concrete primitive types as much as possible.

## What about parameter types introduced by the upstream?

Sometimes, we need to consume the outputs from an upstream pallet, or pass some arguments to it, but the type is parameterized. The type in the upstream is not determined at the pallet level. We don't know the concrete type before it's instantiated in a runtime.

E.g. the follow code cannot build because we cannot assume `BalanceOf<T>` is `u128`:

```rust
Currency::transfer(to, 1000_u128)
```

Two ways to solve the problem. If we are fine with only support the `Currency` type with u128 as the balance type, we can further constrain the dependency by adding a where clause:

```
impl<T: Config> RMRKCore
where
  T: Config<Balance = u128>
```

Full example here: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=3ca8ea5453ef407de15be579bdb7c45a

Another option is to inject a "converter", a struct that can be injected to the config that promises to convert the generic type to a concrete type. This is widely used in XCM:

```
pub trait InstanceIdConverter<T: unique_pallet::Config> {
    fn to_u16(id: T::InstanceId) -> u16;
    fn from_u16(id: u16) -> T::InstanceId;
}
// ...
let id = T::InstanceIdConverter::from_u16(1u16);
let id_u16: u16 = T::InstanceIdConverter::to_u16(id);
```

Full example here: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b091cfeb5008feaba5b5f3a99b743359

**Comment by bmacer** [comment]
Thanks for the thorough analysis.  Taking CollectionId as an example, assuming we want it to be defined as a u32, how would you go about converting this definition in the pallet?  I'm likely overthinking things just from Substrate habit.  Specifically, I've already begun reworking CollectionId to a trait (https://github.com/rmrk-team/rmrk-substrate/tree/rework/rmrk-as-trait) so implementing this change at the same time might be worthwhile, I'm just not sure how.
