### ISSUE TITLE
A need to retrieve all NFTs under a certain address through one query

### ISSUE THREAD

**Issue by doyleguo** [rmrk-team/rmrk-substrate#253]
if we need to get all nfts owned by one user, we need to run several calls to find out all.
1. Call api.query.rmrkCore.collections.entries to get all existing collections.
2. Call api.query.uniques.account.entries(accuntAddress, collectionId) to get all nft ID owned by one users inside specified collection.
3. Call api.query.rmrkCore.nfts.entries(collectionId, nftId) to fetch core metadata for one nft.
4. Call api.query.rmrkCore.properties.entries(collectionId, nftId) to fetch custom properties for one nft.

So when we need get all NFTs belongs to one address and retrieve metadata for these NFTs, we need wait for long time to process it out. If need retrieve all those information essentially, we need some pre-build index service (like SubSquid or SubQuery). PW's API don't provides such capacity now, unfortunately.

**Comment by ilionic** [comment]
Dev UX and performance could be improved with runtime API which would perform multiple storage calls internally with single RPC request. This feature needs to be implemented. 
https://github.com/rmrk-team/rmrk-substrate/blob/main/runtime/src/lib.rs#L503
Additionally pagination could be introduced to fetch in batches.

**Comment by Szegoo** [comment]
@ilionic I will try to make a PR that will close this. I will add a new runtime API call that will perform all of the necessary storage calls to get the NFTs of a user. Also, I will try to add pagination as you said to this since that would be pretty useful here.

**Comment by ilionic** [comment]
> Or did you think of going through each collection so that we return all of the NFTs that are owned by the user?

@Szegoo yeah I think this is what needed to achieve OP request ( to get all nfts of certain address ).
Per collection_id might be useful, too. But needs more planning to define proper runtime API. ie something similar to [EVM](https://evm.rmrk.app/evm-contracts-documentation/rmrk/utils/rmrkequiprenderutils) render utils.
