### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by goheesheng** [rmrk-team/rmrk-substrate#274]
Do we need to compile the contract in the pallets directory? I am confused how to use the codes.

test@test:/Desktop/rmrk-substrate/pallets$ cd rmrk-core/
test@test:/Desktop/rmrk-substrate/pallets/rmrk-core$ cargo contract build 
2023-02-01T23:14:59.771150Z  INFO cargo_contract::crate_metadata: Fetching cargo metadata for Cargo.toml
thread 'main' panicked at 'lib name not found', /home/eesheng/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-contract-1.5.1/src/crate_metadata.rs:65:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by YeoJongHan** [comment]
I cannot find any .ink file after compilation from the root directory

**Comment by ilionic** [comment]
This repository doesn't contain ink contracts, only Substrate pallets

check [rmrk-ink ](https://github.com/rmrk-team/rmrk-ink)
