### ISSUE TITLE
Parachain(s) integration question

### ISSUE THREAD

**Issue by gregzaitsev** [rmrk-team/rmrk-substrate#34]
This is a question about rmrk-core pallet: How heavily is RMRK frontend code married to calls like `mint_nft`, `send`, `add_resource`, as well as architecture when the nesting is the function of the same pallet as nft logic? For example, could we replace `api.tx.rmrkCore.send` with `api.tx.unqiue.transfer`, and `api.tx.rmrkCore.addResource` with `api.tx.nesting.add`?

**Comment by gregzaitsev** [comment]
Also, let's discuss the requirements for `rmrk-core` pallet. What para-chain(s) it is designed for?

**Comment by ilionic** [comment]
Re. Frontend integration - a bit too early. First we are focusing on getting core pallet right. 
Current approach and improved ownership/nesting proposal well described here https://github.com/rmrk-team/rmrk-substrate/issues/27

**Comment by gregzaitsev** [comment]
Uniques pallet is what concerns me the most in current approach. First, it has certain shortcomings, and we will not be including it in our chain: We have implemented a much more powerful set of pallets. Second, it has a bit different interface then unique NFT and RFT pallets. I just gave you access to our repository (it is closed source atm, but we are opening it soon). Please have a look and let’s discuss how to make rmrk-core capable of integrating with both Unique and pallet-uniques.

**Comment by gregzaitsev** [comment]
Sorry for the wrong naming for this issue, the question is more about parachain integration than frontend :) just renamed properly.

**Comment by h4x3rotab** [comment]
Very interested in the NFT pallet you mentioned. So we can assume that there will be multiple implementation of the underlying NFT. Considering RMRK is a "super" super-set of standard NFT functionality, I think the layered approach we have followed is nice -- it should be able to plug to a simple and standard NFT pallet, and provide rich functionalities in an upper layer. As a result, we only need a minimal set of functions provided by the low level NFT pallet.

To me, it sounds like a good time to think about the abstraction of the NFT standard. Then we can define a common trait as a standard for NFT pallets, to hide the the implementation details, just like Substrate's `Currency`.

I don't have a clear idea, but a good start point could be:

1. Have the concept of "Class" (mapped to RMRK's Collection) and "Instance" (RMRK's NFT), and identified by ids
2. Anyone can create a collection and become the owner of it (`Nft::create_class()`)
3. The owner of a collection can mint NFTs (`Nft::mint(class_id, counts)`)
4. A NFT can be transferred (`NFT::transfer(class_id, instance_id, from, to`)
5. A NFT can be burned (`NFT::burn(class_id, instance_id)`)

**Comment by gregzaitsev** [comment]
Could you maybe state what problem are you trying to solve by finding a common NFT standard? This is a tricky task until you have concrete use cases.

**Comment by gregzaitsev** [comment]
Actually, I've just read through your proposal again, and it seems very reasonable to have a minimal set of NFT functions in that common layer like you suggest.

Now can we talk about the actual nesting architecture? We've discussed it with Bruno before and came to a simple design: Alice owns NFTs A and B. The NFT A is transferred to the Nesting pallet (I think this is what you call Equip pallet, not sure this is the most general purpose naming for nesting though). When Nesting/Equip pallet receives the NFT A, it also receives data that it should be owned by the NFT B in the same transaction, so it records the fact that NFT B is owns A. From now on, Alicedoesn't own A anymore, but she owns NFT B, so she can "unbundle" it from A. When Alice transfers NFT B to Dave, Dave receives B, but he also receives A because A is bundled to B. This way, we keep O(1) complexity of transfers, no matter how large is the nesting tree.

Is your understanding of nesting close to what I just described?

**Comment by ilionic** [comment]
@gregzaitsev re. nesting it's actually part of current core pallet ( multi resource + nested nfts ).
We merged recently lazy ownership PR handling such flow as you described: issue https://github.com/rmrk-team/rmrk-substrate/issues/27 and  PR https://github.com/rmrk-team/rmrk-substrate/pull/31

Equip pallet will introduce concept of Base and slots ( we haven't started working on it yet )

**Comment by ilionic** [comment]
Closing it as Unique network defined approach for integration.
