### ISSUE TITLE
Consider pallet owned account_id

### ISSUE THREAD

**Issue by ilionic** [rmrk-team/rmrk-substrate#36]
by h4x3rotab:

```
let (collection_id, nft_id) = Self::nft_mint(
    sender.clone().unwrap_or_default(),
    owner,
    collection_id,
    recipient,
    royalty,
    metadata,
)?;
```

When `sender == None`? If it means the origin is some admin (ProtocolOrigin), I suggest to use pallet's account id instead of the default account id (0x0), which is going to be deprecated soon due to some [security concern](https://github.com/paritytech/substrate/pull/10403).

Example of a pallet owned account_id:
https://github.com/paritytech/substrate/blob/d18705ee7b5b654d3947558fea6dbd0701ac3ecc/frame/society/src/lib.rs#L1733-L1735

**Comment by ilionic** [comment]
@h4x3rotab would you agree with simplified ensure all signed calls in https://github.com/rmrk-team/rmrk-substrate/pull/40 PR?

**Comment by h4x3rotab** [comment]
Looks perfect!
