### ISSUE TITLE
Avoid iteration when checking collection size

### ISSUE THREAD

**Issue by ilionic** [rmrk-team/rmrk-substrate#37]
O(n) scan. Need to think about if we can avoid the iteration here:

```
	fn collection_burn(issuer: T::AccountId, collection_id: CollectionId) -> DispatchResult {
		ensure!(
			NFTs::<T>::iter_prefix_values(collection_id).count() == 0,
```

https://github.com/rmrk-team/rmrk-substrate/blob/main/pallets/rmrk-core/src/functions.rs#L27

**Comment by bmacer** [comment]
Potentially we could add nfts_minted to the collection object, then update it for NFT mint and burn operations?

**Comment by Swader** [comment]
Polkadot uses references heavily across the codebase, like tracking when an account has a balance locked somewhere so it cannot be reaped. Perhaps something that might be useful.

**Comment by ilionic** [comment]
Indeed, substrate docs example [here](https://docs.substrate.io/v3/advanced/account-info/#accountinfo-structure) of account reference counters. 
We should also consider additional storage items ie total collections / nfts count. Would be useful for client side pagination, stats and other things.
