### ISSUE TITLE
fix nftsByOwner getter

### ISSUE THREAD

**Issue by ilionic** [rmrk-team/rmrk-substrate#48]
After merging https://github.com/rmrk-team/rmrk-substrate/pull/31 `nftsByOwner` requires rework. Currently not reflecting correctly

**Comment by HashWarlock** [comment]
Currently `NftsByOwner` is a `StorageMap` with a key of `AccountId` mapped to `Vec<CollectionId, NftId>`. We could use a `StorageNMap` similar to how uniques pallet handles their assets owned by an account:
`Account`
```
#[pallet::storage]
/// The assets held by any given account; set out this way so that assets owned by a single
/// account can be enumerated.
pub(super) type Account<T: Config<I>, I: 'static = ()> = StorageNMap<
	_,
	(
		NMapKey<Blake2_128Concat, T::AccountId>, // owner
		NMapKey<Blake2_128Concat, T::ClassId>,
		NMapKey<Blake2_128Concat, T::InstanceId>,
	),
	(),
	OptionQuery,
>;
```
`remove` & `insert` from the `StorageNMap`
```
Account::<T, I>::remove((&details.owner, &class, &instance));
Account::<T, I>::insert((&dest, &class, &instance), ());
```

`owned`
```
/// Returns an iterator of the asset instances of all classes owned by `who`.
///
/// NOTE: iterating this list invokes a storage read per item.
fn owned(who: &T::AccountId) -> Box<dyn Iterator<Item = (Self::ClassId, Self::InstanceId)>> {
	Box::new(Account::<T, I>::iter_key_prefix((who,)))
}
```

`owned_in_class`
```
/// Returns an iterator of the asset instances of `class` owned by `who`.
///
/// NOTE: iterating this list invokes a storage read per item.
fn owned_in_class(
	class: &Self::ClassId,
	who: &T::AccountId,
) -> Box<dyn Iterator<Item = Self::InstanceId>> {
	Box::new(Account::<T, I>::iter_key_prefix((who, class)))
}
```

**Comment by HashWarlock** [comment]
Would it also be best to store the root owners only & avoid storing the NFT encoded virtual accounts?

**Comment by h4x3rotab** [comment]
Given there's already a reverse index available in uniques, I suggest to just keep user theirs. Very clever design: there's no `Vec<>`, and therefore the performance problem was walked around.

**Comment by bmacer** [comment]
@h4x3rotab what is this reverse indexing available in uniques?

**Comment by h4x3rotab** [comment]
> @h4x3rotab what is this reverse indexing available in uniques?

This one. You can go through all the NFTs root-owned by its owner:

https://github.com/paritytech/substrate/blob/57bf92e42c2ca7f3444567b5ce50d2744fe90b4d/frame/uniques/src/lib.rs#L136

**Comment by bmacer** [comment]
NFtsByOwner removed in #91
