### ISSUE TITLE
should we fail on ACCEPT of a non-pending resource?

### ISSUE THREAD

**Issue by bmacer** [rmrk-team/rmrk-substrate#55]
For an otherwise OK operation, should we fail on an already-ACCEPTed resource?
case 1: alice RESADDs on her own NFT, then ACCEPTs (unnecessary)
case 2: BOB sends to ALICE's NFT, ALICE ACCEPTs, then ACCEPTs again.
assuming we want to add this check, otherwise we'll be sending redundance ResourceAccepted events.

**Comment by h4x3rotab** [comment]
Looks like not reasonable to emit events for redundant resource
