### ISSUE TITLE
Equip pallet setup and scaffolding

### ISSUE THREAD

**Issue by ilionic** [rmrk-team/rmrk-substrate#61]
General Equip pallet setup and integration based on design doc.

**Comment by bmacer** [comment]
one issue to consider... in kanaria, equip operation takes place within the "children" attribute of the parent NFT.  however, we have departed from "Children" in NFT struct in rmrk_core https://github.com/rmrk-team/rmrk-substrate/blob/a395e314e2935d22b32e0204bac488f14712d3d2/traits/src/nft.rs#L22-L34.  as such, should we implement an "Equipment" or "Equippings" StorageMap to hold this info in rmrk-equip?

**Comment by ilionic** [comment]
Addressed in https://github.com/rmrk-team/rmrk-substrate/pull/72
