### ISSUE TITLE
Test Coverage

### ISSUE THREAD

**Issue by SiAlDev** [rmrk-team/rmrk-substrate#68]
Hi, I am new to open source development and would like to participate. Bruno said I should not mention Jira/Confluence but he recommended me creating an issue here :-)

With grcov I have created a test coverage html tree --> https://github.com/SiAlDev/rmrk-substrate/tree/main/target/debug/coverage

I could work on covering all sorts of test scenarios, different data sets etc. I just need a bit guidance to get going.

Best,
Silvio

**Comment by ilionic** [comment]
Hey @SiAlDev 
Thanks for your interest. I think good place to start is core pallet https://github.com/rmrk-team/rmrk-substrate/tree/main/pallets/rmrk-core 
Let me know if you have any questions

**Comment by h4x3rotab** [comment]
Could you add the coverage script to the repo but not commiting the coverage HTML output?

**Comment by SiAlDev** [comment]
@h4x3rotab - I am using gcov with a few command lines which generates the coverage HTML output. You can find it here: https://github.com/mozilla/grcov#example-how-to-generate-gcda-files-for-a-rust-project

**Comment by SiAlDev** [comment]
Hi @ilionic, the test coverage and tests are looking quite good. I am still learning and try to create a simple front end for the RMRK-pallet. I would like to use the kitten template from the substrate tutorial and have the basic functionalities implemented. This way I learn about the front- and back-end and it might even be useful for others..

Now I stuck. I have created a question on stackoverflow --> https://stackoverflow.com/questions/71391956/how-to-use-the-multi-method

I uploaded my current code here:
https://github.com/SiAlDev/substrate-front-end-template/tree/rmrk

Could you help me on this one? Or give further information/documentation/tutorials to learn? Thank you!!

**Comment by SiAlDev** [comment]
I was able to solve the problem and can now display the collections :-)

<img width="1255" alt="Screenshot 2022-03-10 at 7 20 32 AM" src="https://user-images.githubusercontent.com/13958257/157555830-05c231bc-5fee-452b-a97e-36b57a73d643.png">

**Comment by SiAlDev** [comment]
I progressed a bit further and added the 'Create Collection' function to the button. Adding works now. I also added the 'Destroy Collection' function.

Now, I am confused with the IDs.

`await api.query.rmrkCore.collections.entries(collections => { ...` 
The query above returns a map of key and values:

- key: collectionId e.G. 0x5bef2c5471aa9e955551dc810f5abb399200647b8c99af7b8b52752114831bdb74e76a9656c0445715000000
- values (createdAtHash, issuer, metadata, max, symbol, nftsCount)

However, when I try to destroy a collection, a collectionId is requested - but this should be in the format of u32. But with the event rmrkCore:CollectionCreated only the issuer address is returned --> ["5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY","20"]


**Now my question is: Where do I find the address of the collection? Or is there a way to convert the hash (0x5be...) to u32 (5Grwva)?**

<img width="548" alt="Screenshot 2022-03-17 at 11 13 24 AM" src="https://user-images.githubusercontent.com/13958257/158729357-f9123de1-df4f-4cfc-ac8e-0aa0a0649308.png">

**Comment by ilionic** [comment]
@SiAlDev sorry for not answering to previous messages. Missed github notifications and then didn’t realize this discussion about front end is in Test Coverage issue. 
Seems like you progressed with client side further than we, I started working on it very recently.
Will get back to you

**Comment by SiAlDev** [comment]
That would be awesome!
