### ISSUE TITLE
Add replace-resource ID

### ISSUE THREAD

**Issue by Swader** [rmrk-team/rmrk-substrate#73]
When adding a new resource, an issuer should be able to specify the ID of an existing one which would get overwritten. This is necessary to be able to upgrade NFTs, change their parts, or even just do reveal mechanics of certain types.

This should be an extra parameter passed alongside the add resource call.

**Comment by bmacer** [comment]
This seems to have been started with #72, which changes ResourceId from auto-incrementing to arbitrary and client-specified. 
https://github.com/rmrk-team/rmrk-substrate/blob/7dd526424715be8d65943cd26b9410a3a52ff57b/pallets/rmrk-core/src/lib.rs#L543
