### ISSUE TITLE
burnNft leaves resources

### ISSUE THREAD

**Issue by bmacer** [rmrk-team/rmrk-substrate#80]
burnNft successfully destroys the NFT storage for the NFT, but Resources is stored separately (in Resources storage).  burn operation doesn't destroy this storage, which it should.

repro:
create collection
create nft
add resource to nft
burn nft
check resources storage (it will still be there)

**Comment by Yuripetusko** [comment]
This is the case with uniques pallet as well to be honest, so it's expected from the clients to batch multiple transactions to destroy resources, attributes and NFT.

I do agree tho that it doesn't make much sense.

**Comment by bmacer** [comment]
I think we can pretty easily add the resource destruction into the code, this should be an easy one to resolve, I was just in a bug-hunting mood.  Will get into bug-zapping mood soon I do believe.
