### ISSUE TITLE
Convert Collection ID and NFT ID to BoundedVec

### ISSUE THREAD

**Issue by bmacer** [rmrk-team/rmrk-substrate#83]
I believe we should convert Collection ID and NFT ID values from u32 to BoundedVec.  The current way is incrementally indexed (Collection 0, 1, 2, etc).  Proposal is to switch to user-defined symbols of some max length.  I think one drawback would be storage size, but the benefits would be usability and likely cross-chain functionality.

Consider create collection KANBIRD and NFT of this collection SUPERFOUNDER_1.  The collection ID/NFT ID tuple would be (KANBIRD, SUPERFOUNDER_1) as opposed to (0, 0).  Obviously this would make interaction with the pallet more user-friendly.  Also, I suspect cross-chain activities will be easier.  Transferring across chain would only (conceptually) fail if the NFT (KANBIRD, SUPERFOUNDER_1) already exists on the destination change (less likely than (0, 0) obviously).

There are a few challenges in developing this way, as we currently have some reliance on the numbering of Collection ID (specifically I'm thinking of collection max count) but I believe this can be overcome pretty easily.

Resource ID is already implemented this way, and seems to be surviving like this.

**Comment by HashWarlock** [comment]
This is not optimal as it will introduce more overhead as it scales and will also break the Lazy Ownership. There could be an off-chain indexer that can map collection ids/nft ids in this manner. I believe we want to ensure we store as little on the blockchain as possible since Storage is expensive.

**Comment by bmacer** [comment]
can you clarify what you mean by lazy ownership?

**Comment by HashWarlock** [comment]
Lazy Ownership being the implementation from issue #27 and we would no longer be in sync with `pallet_uniques`. All our calls to `pallet_uniques` functions like `do_mint`, `do_transfer`, `do_burn`, and any other function will no longer work if we moved to `BoundedVec`

**Comment by bmacer** [comment]
I think we can close this question

**Comment by HashWarlock** [comment]
We could potentially reopen or create a new issue on this now. I think it is reasonable to alter this to be an issue to accept `BoundedVec`'s for `ResourceId` and `NftId`.
