### ISSUE TITLE
rmrkCore.setProperty extrinsic fires an event twice

### ISSUE THREAD

**Issue by amatsonkali** [rmrk-team/rmrk-substrate#87]
Two identical `rmrkCore.PropertySet` events are being registered when a property is set succesfully:

![Captura de pantalla de 2022-03-02 11-10-09](https://user-images.githubusercontent.com/43050815/156413052-3d610235-2aa9-4e8c-ac26-6e879d45e672.png)
The events contain exactly the same values (collection_id, maybe_nft_id, key, value)

**Comment by bmacer** [comment]
thanks for reporting!
submitted #89 to fix this.  i'll merge once the tests pass (in a few minutes hopefully).
thanks again.  looking forward to future issue reports.

**Comment by ilionic** [comment]
fix merged, thanks
