### ISSUE TITLE
Implement Royalties

### ISSUE THREAD

**Issue by bhgomes** [rmrk-team/rmrk-substrate#96]
I saw that the minting process can setup the royalty percentage for an NFT but it seems that the actual royalties are not sent during a transfer or a market sale. Has it not been implemented yet or does other code in a different repo implement this?

**Comment by ilionic** [comment]
Royalties information should be there, logged alongside the nft - but for dapps and UIs to respect. [See more](https://app.subsocial.network/@bruno/on-chain-royalties-for-nf-ts-are-un-enforceable-18777)

**Comment by bhgomes** [comment]
Ok, thanks so much for the reference, I hadn't yet considered all the incentives involved that make "enforceable royalties" impossible at the moment.
